petco = Store.find_or_create_by(name: "Petco")
bestbuy = Store.find_or_create_by(name: "Best Buy")
wholefoods = Store.find_or_create_by(name: "Whole Foods")
dicks = Store.find_or_create_by(name: "DICKS Sporting Goods")
walgreens = Store.find_or_create_by(name: "Walgreens")

banana = Item.find_or_create_by(name: "Banana")
milk = Item.find_or_create_by(name: "Milk")
bread = Item.find_or_create_by(name: "Bread")
organic_granola = Item.find_or_create_by(name: "Organic Granola")
free_range_eggs = Item.find_or_create_by(name: "Free Range Eggs")
tv = Item.find_or_create_by(name: "TV")
headphones = Item.find_or_create_by(name: "Headphones")
video_game = Item.find_or_create_by(name: "Video Game")
smart_watch = Item.find_or_create_by(name: "Smart Watch")
phone_charger = Item.find_or_create_by(name: "Phone Charger")
cleats = Item.find_or_create_by(name: "Cleats")
football = Item.find_or_create_by(name: "Football")
golf_club = Item.find_or_create_by(name: "Golf Club")
soccer_net = Item.find_or_create_by(name: "Soccer Net")
baseball = Item.find_or_create_by(name: "Baseball")
prescription_drug = Item.find_or_create_by(name: "Prescription Medicine")
comb = Item.find_or_create_by(name: "Comb")
toothbrush = Item.find_or_create_by(name: "Toothbrush")
candy = Item.find_or_create_by(name: "Candy")
soda = Item.find_or_create_by(name: "Soda")
dog_food = Item.find_or_create_by(name: "Dog Food")
litterbox = Item.find_or_create_by(name: "Litterbox")
leash = Item.find_or_create_by(name: "Leash")


# StoreItem.find_or_create_by()
